name: Docker build

on:
  workflow_dispatch:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/search:${GITHUB_SHA::8} -t ${{ secrets.DOCKERHUB_USERNAME }}/search:latest -f docker/search.Dockerfile .
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/interview:${GITHUB_SHA::8} -t ${{ secrets.DOCKERHUB_USERNAME }}/interview:latest -f docker/interview.Dockerfile .
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/auth:${GITHUB_SHA::8} -t ${{ secrets.DOCKERHUB_USERNAME }}/auth:latest -f docker/auth.Dockerfile .
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app:${GITHUB_SHA::8} -t ${{ secrets.DOCKERHUB_USERNAME }}/app:latest -f docker/app.Dockerfile .

      - name: Push the images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/search:${GITHUB_SHA::8}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/interview:${GITHUB_SHA::8}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/auth:${GITHUB_SHA::8}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/app:${GITHUB_SHA::8}