name: buildx

on:
  workflow_dispatch:
  push:
    branches:
      - deploy

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/arm/v6,linux/arm/v7,linux/arm/v8,linux/arm64 \
            --output "type=image,push=false" \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/hahaton:latest . \
      - name: Push the images
          run: |
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/hahaton:latest