name: Docker build
uses: crazy-max/ghaction-docker-buildx@v3.3.1


on:
  workflow_dispatch:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hahaton:latest .

      - name: Push the images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/hahaton:latest